/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APAREN = 8;
  /** RegularExpression Id. */
  int FPAREN = 9;
  /** RegularExpression Id. */
  int PTOVIRGULA = 10;
  /** RegularExpression Id. */
  int ATRIB = 11;
  /** RegularExpression Id. */
  int VIRGULA = 12;
  /** RegularExpression Id. */
  int ADD = 13;
  /** RegularExpression Id. */
  int SUB = 14;
  /** RegularExpression Id. */
  int MULT = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int MENOR = 19;
  /** RegularExpression Id. */
  int MAIOR = 20;
  /** RegularExpression Id. */
  int IGUAL = 21;
  /** RegularExpression Id. */
  int TIPOD = 22;
  /** RegularExpression Id. */
  int VAR = 23;
  /** RegularExpression Id. */
  int PRINT = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int FUNCTION = 26;
  /** RegularExpression Id. */
  int IF = 27;
  /** RegularExpression Id. */
  int ELSE = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int WHILE = 30;
  /** RegularExpression Id. */
  int BVAL = 31;
  /** RegularExpression Id. */
  int NUM = 32;
  /** RegularExpression Id. */
  int ID = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":=\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "<TIPOD>",
    "\"var\"",
    "\"print\"",
    "\"return\"",
    "\"function\"",
    "\"if\"",
    "\"else\"",
    "\"do\"",
    "\"while\"",
    "<BVAL>",
    "<NUM>",
    "<ID>",
  };

}
